version: '3'

volumes:
  static_value:
  media_value:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/taski_backend:latest
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/taski_frontend:latest
    env_file: .env

  gateway:
    image: ${{ secrets.DOCKER_USERNAME }}/taski_gateway:latest
    ports:
      - "8000:80"